doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  connections:
    default:
      server: "%env(resolve:MONGODB_URL)%"
      options: {}
  default_database: "%env(MONGODB_DB)%"
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App\Document:
          dir: "%kernel.project_dir%/src/Document"
          prefix: 'App\Document'
