nelmio_cors:
  defaults:
    allow_origin: ["http://127.0.0.1:3307"]
    allow_credentials: true
    allow_headers: ["Content-Type", "Authorization", "X-AUTH-TOKEN"]
    expose_headers: ["Link"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
    max_age: 3600
  paths:
    "^/api/": # S'assure que tous les endpoints API sont couverts
      allow_origin: ["http://127.0.0.1:3307"]
