nelmio_cors:
  defaults:
    allow_origin:
      - "http://127.0.0.1:3307"
      - "http://localhost:3307"
    allow_credentials: true
    allow_headers:
      - "Content-Type"
      - "Authorization"
      - "X-AUTH-TOKEN"
    expose_headers:
      - "Link"
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    max_age: 3600
  paths:
    "^/api/":
      allow_origin:
        - "http://127.0.0.1:3307"
        - "http://localhost:3307"
      allow_credentials: true
    "^/like/":
      allow_origin:
        - "http://127.0.0.1:3307"
        - "http://localhost:3307"
      allow_methods:
        - "POST"
        - "OPTIONS"
      allow_headers:
        - "Content-Type"
        - "Authorization"
        - "X-AUTH-TOKEN"
      max_age: 3600
    "^/likes$":
      allow_origin:
        - "http://127.0.0.1:3307"
        - "http://localhost:3307"
      allow_methods:
        - "GET"
        - "OPTIONS"
      allow_headers:
        - "Content-Type"
        - "Authorization"
        - "X-AUTH-TOKEN"
      max_age: 3600
